apiVersion: v1
kind: Pod
metadata:
  name: ubi9-tools
spec:
  terminationGracePeriodSeconds: 3
  containers:
    - name: ubi
      image: image-registry.openshift-image-registry.svc:5000/atos-development/ubi9-tools
      command:
        - bash
        - '-c'
        - |
          while true ; do sleep 2; done