kind: CronJob
apiVersion: batch/v1
metadata:
  name: db-migrations
spec:
  # Disabled because triggered manually
  schedule: "0 0 31 2 *"
  suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: db-migrations
      annotations:
        prometheus.io/scrape: 'false'
    spec:
      template:
        spec:
          containers:
            - name: db-migrations
              image: quay.io/tailorshift/db:latest
              args:
                - migrate
              env:
                - name: FLYWAY_URL
                  valueFrom:
                    secretKeyRef:
                      name: pg-datacenter-pguser-pg-datacenter
                      key: jdbc-uri
              imagePullPolicy: Always
          restartPolicy: Never
