# Naming convention of this configMap according to
# https://access.crunchydata.com/documentation/postgres-operator/4.6.2/advanced/custom-configuration/#modifying-postgresql-cluster-configuration
kind: ConfigMap
apiVersion: v1
metadata:
  name: pg-datacenter-pgha-config
  namespace: {{ .Release.Namespace }}
data:
  # Configuring a replication slot for the Debezium pgoutput plug-in
  # https://access.redhat.com/documentation/de-de/red_hat_integration/2022.q1/html/debezium_user_guide/debezium-connector-for-postgresql#configuring-a-replication-slot-for-the-debezium-pgoutput-plug-in
  pg-datacenter-dcs-config: |-
    postgresql:
      parameters:
        wal_level: logical
        max_wal_senders: 1
        max_replication_slots: 1
