apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pg-datacenter
  namespace: {{ .Release.Namespace }}
  labels:
    app: infrastructure
spec:
  users:
    - name: pg-datacenter
      databases:
        - pg-datacenter
    - name: debezium
      databases:
        - pg-datacenter
      options: "REPLICATION"
  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      name: ''
      replicas: 1
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          # Configuring a replication slot for the Debezium pgoutput plug-in
          # https://access.redhat.com/documentation/de-de/red_hat_integration/2022.q1/html/debezium_user_guide/debezium-connector-for-postgresql#configuring-a-replication-slot-for-the-debezium-pgoutput-plug-in
          wal_level: logical
          max_wal_senders: 1
          max_replication_slots: 1
  port: 5432
  postgresVersion: 13