kind: Deployment
apiVersion: apps/v1
metadata:
  name: pos_manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: pos_manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos_manager
  template:
    metadata:
      labels:
        app: pos_manager
    spec:
      containers:
        - name: container
          image: 'quay.io/tailorshift/pos_manager:1.0.0-SNAPSHOT'
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: pg-datacenter-pguser-pg-datacenter
                  key: jdbc-uri
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst