apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-kafka-postgres-connect
  annotations:
    strimzi.io/use-connector-resources: "true" 
    argocd.argoproj.io/sync-wave: "10"
spec:
  version: "3.00"
  bootstrapServers: kafka-datacenter-kafka-bootstrap:9093
  build: 
    output: 
      type: imagestream  
      image: debezium-streams-connect:latest
    plugins: 
      - name: debezium-connector-postgres
        artifacts:
          - type: zip
            url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/1.9.7.Final-redhat-00003/debezium-connector-postgres-1.9.7.Final-redhat-00003-plugin.zip  
  