kind: Deployment
apiVersion: apps/v1
metadata:
  name: registration-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: registration-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-service
  template:
    metadata:
      labels:
        app: registration-service
    spec:
      containers:
        - name: container
          image: 'quay.io/tailorshift/registration-service:1.0.0'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: pg-datacenter-pguser-pg-datacenter
                  key: jdbc-uri
            - name: K8S_NAMESPACE
              value: atos-development
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccount: cert-manager-self-service