kind: ServiceAccount
apiVersion: v1
metadata:
  name: cert-manager-self-service
  namespace: {{ .Release.Namespace }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-self-service
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - cert-manager.io
    resources:
      - certificates

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-self-service
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: cert-manager-self-service
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-self-service
