kind: Service
apiVersion: v1
metadata:
  name: registration-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: registration-service
