kind: ConfigMap
apiVersion: v1
metadata:
  name: manufacturing-server
  namespace: {{ .Release.Namespace }}
data:
  convert-cert.sh: |-
    ls -lah /keys
    cp /keys/*.pem /etc/fdo/keys/
    openssl pkcs8 -topk8 -inform PEM -outform DER -in /keys/manufacturer_key.key -out /etc/fdo/keys/manufacturer_key.der -nocrypt
    openssl pkcs8 -topk8 -inform PEM -outform DER -in /keys/diun_cert.key -out /etc/fdo/keys/diun_cert.der -nocrypt
    openssl pkcs8 -topk8 -inform PEM -outform DER -in /keys/owner_cert.key -out /etc/fdo/keys/owner_cert.der -nocrypt
    openssl pkcs8 -topk8 -inform PEM -outform DER -in /keys/device_ca_key.key -out /etc/fdo/keys/device_ca_key.der -nocrypt
    ls -lah /etc/fdo/keys
  config.yml: |-
    ---
    session_store_driver:
      Directory:
        path: /etc/fdo/stores/manufacturing_sessions/
    ownership_voucher_store_driver:
      Directory:
        path: /etc/fdo/stores/owner_vouchers
    public_key_store_driver:
      Directory:
        path: /etc/fdo/stores/manufacturer_keys
    bind: "0.0.0.0:8080"
    protocols:
      plain_di: false
      diun:
        mfg_string_type: SerialNumber
        key_type: SECP384R1
        allowed_key_storage_types:
          - Tpm
          - FileSystem
        key_path: /etc/fdo/keys/diun_key.der
        cert_path: /etc/fdo/keys/diun_cert.pem
    rendezvous_info:
      - deviceport: 8082
        dns: fdo-rendezvous-server-atos-development.apps.wa6eqszp.uksouth.aroapp.io
        ownerport: 443
        protocol: https
    manufacturing:
      manufacturer_cert_path: /etc/fdo/keys/manufacturer_cert.pem
      device_cert_ca_private_key: /etc/fdo/keys/device_ca_key.der
      device_cert_ca_chain: /etc/fdo/keys/device_ca_cert.pem
      owner_cert_path: /etc/fdo/keys/owner_cert.pem
      manufacturer_private_key: /etc/fdo/keys/manufacturer_key.der
