apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fdo-manufacturing-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - manufacturing.tailorshift.com
  issuerRef:
    kind: Issuer
    name: tailorshift-ca-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: fdo-manufacturing-cert
