kind: Service
apiVersion: v1
metadata:
  name: fdo-owner-onboarding-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: fdo-owner-onboarding-server
