kind: ConfigMap
apiVersion: v1
metadata:
  name: fdo-owner-onboarding-server
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    ---
    session_store_driver:
      Directory:
        path: /etc/fdo/stores/owner_onboarding_sessions
    ownership_voucher_store_driver:
      Directory:
        path: /etc/fdo/stores/owner_vouchers
    trusted_device_keys_path: /etc/fdo/keys/device_ca_cert.pem
    owner_private_key_path: /etc/fdo/keys/owner_key.der
    owner_public_key_path: /etc/fdo/keys/owner_cert.pem
    owner_addresses:
      - transport: HTTP
        port: 8080
        addresses:
          - dns_name: fdo.tailorshift.com
    report_to_rendezvous_endpoint_enabled: false
    bind: 0.0.0.0:8080
    service_info_api_url: "http://localhost:8089/device_info"
    service_info_api_authentication: None