kind: ConfigMap
apiVersion: v1
metadata:
  name: fdo-rendezvous-server
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    ---
    storage_driver:
      Directory:
        path: /etc/fdo/stores/rendezvous_registered
    session_store_driver:
      Directory:
        path: /etc/fdo/stores/rendezvous_sessions
    trusted_manufacturer_keys_path: /etc/fdo/keys/manufacturer_cert.pem
    max_wait_seconds: ~
    bind: "0.0.0.0:8080"