kind: Deployment
apiVersion: apps/v1
metadata:
  name: serviceinfo-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: serviceinfo-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceinfo-api-server
  template:
    metadata:
      labels:
        app: serviceinfo-api-server
    spec:
      containers:
        - name: container
          image: quay.io/fido-fdo/serviceinfo-api-server
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/fdo/serviceinfo-api-server.conf.d/
            - name: device-specific-serviceinfo
              mountPath: /etc/fdo/device_specific_serviceinfo
            - name: sessions
              mountPath: /etc/fdo/sessions
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      volumes:
        - name: config
          configMap:
            name: serviceinfo-api-server
        - name: device-specific-serviceinfo
          emptyDir: {}
        - name: sessions
          emptyDir: {}
