kind: Service
apiVersion: v1
metadata:
  name: serviceinfo-api-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: serviceinfo-api-server
