kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: serviceinfo-api-server
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: serviceinfo-api-server
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
