kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fdo-stores
  namespace: {{ .Release.Namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile-csi
  volumeMode: Filesystem
