kind: Deployment
apiVersion: apps/v1
metadata:
  name: pos-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: pos-manager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-manager
  template:
    metadata:
      labels:
        app: pos-manager
    spec:
      containers:
        - name: container
          image: 'quay.io/tailorshift/pos-manager:1.0.0-SNAPSHOT'
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: pg-backoffice-pguser-pg-backoffice
                  key: jdbc-uri
            - name: INVENTORY_MANAGER_URL
              value: https://inventory-manager-atos-development.apps.wa6eqszp.uksouth.aroapp.io
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst