kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: pos-manager
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: pos-manager
    weight: 100
  port:
    targetPort: 8081
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
