apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: atos-development
spec:
  destination:
    namespace: atos-development
    server: https://kubernetes.default.svc
  project: default
  source:
    path: datacenter/charts/cert-manager
    repoURL: git@github.com:TailorShift/IaC.git
    targetRevision: HEAD