apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registration-service
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: datacenter/charts/registration-service
    repoURL: git@github.com:TailorShift/IaC.git
    targetRevision: HEAD