kind: ConfigMap
apiVersion: v1
metadata:
  name: replication-manager
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka-datacenter-kafka-bootstrap.atos-development.svc.cluster.local:9092