apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replication-manager
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backoffice/charts/replication-manager
    repoURL: git@github.com:TailorShift/IaC.git
    targetRevision: HEAD