apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-aoa
  namespace: atos-shop-back-office
spec:
  destination:
    namespace: atos-shop-back-office
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backoffice/apps
    repoURL: git@github.com:TailorShift/IaC.git
    targetRevision: HEAD
