kind: ConfigMap
apiVersion: v1
metadata:
  name: replication-manager
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka-backoffice-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local:9092