# This is a secret used to protect the java keystore files
# Hardcoding the password for simplicity here. Should be mounted via external secrets operator that is not available...
apiVersion: v1
kind: Secret
metadata:
  name: java-keystore
  namespace: {{ .Release.Namespace }}
stringData:
  password: banana
