apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tailorshift-ca-certificate
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: tailorshift-ca-certificate
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: self-signed-issuer
    kind: Issuer
    group: cert-manager.io
  # This will create a keystores.jks and a truststore.jks containing the root ca information
  keystores:
    jks:
      create: true
      passwordSecretRef:
        name: java-keystore
        key: password