apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    usage: pos-edge
  name: tailorshift-pos-device-sample
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - device-sample.tailorshift.com
  issuerRef:
    kind: Issuer
    name: tailorshift-ca-issuer
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: java-keystore
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  secretName: tailorshift-pos-device-sample
  secretTemplate:
    labels:
      usage: pos-edge
      deviceId: sample
  usages:
    - server auth
    - client auth
