kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafdrop
  namespace: atos-development
  labels:
    app: kafdrop
spec:
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
        authType-SupportUser: 'true'
        version: '1'

    spec:
      containers:
        - name: kafdrop
          image: 'obsidiandynamics/kafdrop:latest'
          ports:
            - containerPort: 9000
          env:
            - name: JVM_OPTS
              value: '-Xms512M -Xmx1024M'
            - name: KAFKA_BROKERCONNECT
              value: 'kafka-datacenter-kafka-bootstrap.atos-development.svc:9092'
            - name: SERVER_SERVLET_CONTEXTPATH
              value: '/'
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: remote-docker-registry
      securityContext: {}
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: kafdrop
  namespace: atos-development
  labels:
    app: kafdrop
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: kafdrop
  type: ClusterIP