apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: kafka-connect
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: debezium-kafka-postgres-connector
  namespace: {{ .Release.Namespace }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector 
  tasksMax: 1  
  config:  
    database.history.kafka.bootstrap.servers: kafka-datacenter-kafka-bootstrap.{{ .Release.Namespace }}.svc.cluster.local:9092
    database.history.kafka.topic: TailorShift.datacenter
    database.hostname: ${secrets:{{ .Release.Namespace }}/pg-datacenter-pguser-debezium:host}
    database.port: ${secrets:{{ .Release.Namespace }}/pg-datacenter-pguser-debezium:port}
    database.user: ${secrets:{{ .Release.Namespace }}/pg-datacenter-pguser-debezium:user}
    database.password: ${secrets:{{ .Release.Namespace }}/pg-datacenter-pguser-debezium:password}
    database.dbname: ${secrets:{{ .Release.Namespace }}/pg-datacenter-pguser-debezium:dbname}
    database.server.name: pg-datacenter
    table.include.list: public.customers,public.employees,public.inventory_movements,public.pos_devices,public.products
    decimal.handling.mode: string
    publication.autocreate.mode: filtered
    plugin.name: pgoutput