apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mm2-pulling-datacenter
  namespace: {{ .Release.Namespace }}
spec:
  clusters:
    - alias: kafka-backoffice
      bootstrapServers: >-
        kafka-backoffice-kafka-bootstrap-atos-shop-back-office.apps.hzkv4yuz.uksouth.aroapp.io:443
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: kafka-backoffice-ca
    - alias: kafka-datacenter
      bootstrapServers: >-
        kafka-datacenter-kafka-bootstrap.atos-development.svc.cluster.local:9092
  connectCluster: kafka-datacenter
  mirrors:
    - checkpointConnector:
        config:
          emit.checkpoints.interval.seconds: 60
          refresh.groups.interval.seconds: 60
          sync.group.offsets.enabled: true
          sync.group.offsets.interval.seconds: 60
      sourceCluster: kafka-backoffice
      sourceConnector:
        config:
          refresh.topics.interval.seconds: 60
          sync.topic.acls.enabled: true
      targetCluster: kafka-datacenter
      topicsPattern: pg-backoffice.*
  replicas: 1
  version: 3.3.1