apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: kafka-connect
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: debezium-kafka-postgres-connector
  namespace: {{ .Release.Namespace }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector 
  tasksMax: 1  
  config:  
    database.history.kafka.bootstrap.servers: kafka-datacenter-kafka-bootstrap.atos-development.svc.cluster.local:9092
    database.history.kafka.topic: TailorShift.datacenter
    database.hostname: pg-datacenter-primary.atos-development.svc.cluster.local
    database.port: 5432
    database.user:  ${secrets:{{ .Release.Namespace }}/debezium-secret:username}
    database.password:  ${secrets:{{ .Release.Namespace }}/debezium-secret:password}
    database.dbname: pg-datacenter
    database.server.name: pg-datacenter
    table.include.list: public.customers,public.customers,public.employees,public.inventory_movements,public.public.pos_devices,public.products