kind: Deployment
apiVersion: apps/v1
metadata:
  name: inventory-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: inventory-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-manager
  template:
    metadata:
      labels:
        app: inventory-manager
    spec:
      containers:
        - name: container
          image: 'quay.io/tailorshift/inventory-manager:1.0.0'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: pg-datacenter-pguser-pg-datacenter
                  key: jdbc-uri
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst